tests:
  - type: run-cmd
    cmd: [build:test_proc_reduce]
    profiles: [release]
    limits:
      cpu_ms_per_sec: 4000
      wall_time_sec: 50
  - type: report-score
    task: proc-reduce
editable:
  - reduce.hpp
