[[project]]
path = "common/syscalls/src/x86_64"
instruction_set = "x86/x86-64"
assembler = "gas"

[[project]]
path = "common/syscalls/src/aarch64"
instruction_set = "arm"
assembler = "gas"

[[project]]
path = "common/caos_nostd/src/x86_64"
instruction_set = "x86/x86-64"
assembler = "gas"

[[project]]
path = "common/caos_nostd/src/aarch64"
instruction_set = "arm"
assembler = "gas"
