tests:
  - type: run-cmd
    cmd: [python3, tool:nej-runner, --checker, cmp, --run-cmd, build:solution_backtrace]
    profiles:
      - debug
      - asan
  - type: report-score
    task: backtrace
editable:
  - solution.S
