tests:
  - type: run-cmd
    profiles:
      - tsan
      - asan
      - release
    cmd: [build:test_limbo]
    limits:
      procs: 120
      wall_time_sec: 20
  - type: report-score
    task: limbo
editable:
  - limbo.hpp
